org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=26.2
fabric_loader_version=0.19.3
loom_version=1.17-SNAPSHOT
fabric_api_version=0.159.0+26.2

mod_id=naturalist
mod_name=Naturalist
mod_version=2.0.3+26.2.port.4
mod_group_id=com.crispytwig.naturalist
