org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]

enabled_platforms=fabric,neoforge

neo_version=21.1.234
loader_version_range=[1,)

fabric_loader_version=0.19.3
fabric_api_version=0.116.4+1.21.1

lambdynamiclights_version=4.8.8+1.21.1
justenoughbreeding_fabric_version=NRXUaZbv
justenoughbreeding_neoforge_version=SMcvKJOF
emi_fabric_version=1.1.24+1.21.1+fabric
emi_neoforge_version=1.1.24+1.21.1+neoforge
field_guide_fabric_version=1.13.2-1.21.1-fabric
field_guide_neoforge_version=1.13.2-1.21.1-neoforge
immersive_overlays_version=1.6.1+1.21.1
not_enough_animations_fabric_version=HyecdWuC
not_enough_animations_neoforge_version=eYNogep3
personality_neoforge_version=GQKsKYS3
blueprint_neoforge_version=LMGtMapI

mod_id=naturalist
mod_name=Naturalist
mod_license=MIT
mod_version=2.0.2
mod_group_id=com.crispytwig.naturalist
mod_authors=crispytwig, Starfish Studios
mod_description=Enhances the overworld by adding new wildlife with unique behavior!

curseforge=627986
modrinth=F8BQNPWX
