architectury {
    common rootProject.enabled_platforms.split(",")
}

loom {
    accessWidenerPath = file("src/main/resources/naturalist.accesswidener")
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:${project.fabric_loader_version}"
    modCompileOnly "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"


    modCompileOnly("dev.lambdaurora.lambdynamiclights:lambdynamiclights-api:${project.lambdynamiclights_version}")

    modCompileOnly "maven.modrinth:field-guide:${project.field_guide_fabric_version}"

    compileOnly "org.jetbrains:annotations:24.1.0"
    compileOnly "org.jspecify:jspecify:1.0.0"
}
