modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/starfish-studios/Naturalist/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="icon.png"
authors="${mod_authors}"
description='''${mod_description}'''

[[mixins]]
config="naturalist.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="geckolib"
    type="required"
    versionRange="[4.7,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="lambdynlights_api"
    type="optional"
    versionRange="[4.0.0,)"
    ordering="AFTER"
    side="CLIENT"

[modproperties.${mod_id}."yumi:entrypoints"]
    "lambdynlights:initializer" = ["com.starfish_studios.naturalist.client.compat.LambDynamicLightsCompat"]
