package com.starfish_studios.naturalist.server.level.modifiers;

import com.mojang.serialization.MapCodec;
import com.starfish_studios.naturalist.NaturalistConfig;
import com.starfish_studios.naturalist.registry.NaturalistEntityTypes;
import com.starfish_studios.naturalist.registry.NaturalistTags;
import com.starfish_studios.naturalist.registry.NaturalistBiomeModifiers;
import net.minecraft.core.Holder;
import net.minecraft.tags.BiomeTags;
import net.minecraft.tags.TagKey;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.MobCategory;
import net.minecraft.world.level.biome.Biome;
import net.minecraft.world.level.biome.MobSpawnSettings;
import net.neoforged.neoforge.common.world.BiomeModifier;
import net.neoforged.neoforge.common.world.ModifiableBiomeInfo;
import org.jetbrains.annotations.NotNull;

public class AddAnimalsBiomeModifier implements BiomeModifier {
    @Override
    public void modify(@NotNull Holder<Biome> biome, Phase phase, ModifiableBiomeInfo.BiomeInfo.@NotNull Builder builder) {
        if (phase.equals(Phase.ADD)) {
             if (NaturalistConfig.COMMON_CONFIG.alligatorSpawnWeight.get() != 0 && !biome.is(NaturalistTags.Biomes.BLACKLIST_ALLIGATOR)) addMobSpawn(builder, biome, NaturalistTags.Biomes.HAS_ALLIGATOR, MobCategory.CREATURE, NaturalistEntityTypes.ALLIGATOR.get(), NaturalistConfig.COMMON_CONFIG.alligatorSpawnWeight.get(), NaturalistConfig.COMMON_CONFIG.alligatorSpawnMinGroupSize.get(), NaturalistConfig.COMMON_CONFIG.alligatorSpawnMaxGroupSize.get());
             if (NaturalistConfig.COMMON_CONFIG.bassSpawnWeight.get() != 0 && !biome.is(NaturalistTags.Biomes.BLACKLIST_BASS)) addMobSpawn(builder, biome, NaturalistTags.Biomes.HAS_BASS, MobCategory.WATER_AMBIENT, NaturalistEntityTypes.BASS.get(), NaturalistConfig.COMMON_CONFIG.bassSpawnWeight.get(), NaturalistConfig.COMMON_CONFIG.bassSpawnMinGroupSize.get(), NaturalistConfig.COMMON_CONFIG.bassSpawnMaxGroupSize.get());
             if (NaturalistConfig.COMMON_CONFIG.bearSpawnWeight.get() != 0 && !biome.is(NaturalistTags.Biomes.BLACKLIST_BEAR)) addMobSpawn(builder, biome, NaturalistTags.Biomes.HAS_BEAR, MobCategory.CREATURE, NaturalistEntityTypes.BEAR.get(), NaturalistConfig.COMMON_CONFIG.bearSpawnWeight.get(), NaturalistConfig.COMMON_CONFIG.bearSpawnMinGroupSize.get(), NaturalistConfig.COMMON_CONFIG.bearSpawnMaxGroupSize.get());
             if (NaturalistConfig.COMMON_CONFIG.bluejaySpawnWeight.get() != 0 && !biome.is(NaturalistTags.Biomes.BLACKLIST_BLUEJAY)) addMobSpawn(builder, biome, NaturalistTags.Biomes.HAS_BLUEJAY, MobCategory.CREATURE, NaturalistEntityTypes.BLUEJAY.get(), NaturalistConfig.COMMON_CONFIG.bluejaySpawnWeight.get(), NaturalistConfig.COMMON_CONFIG.bluejaySpawnMinGroupSize.get(), NaturalistConfig.COMMON_CONFIG.bluejaySpawnMaxGroupSize.get());
             if (NaturalistConfig.COMMON_CONFIG.boarSpawnWeight.get() != 0 && !biome.is(NaturalistTags.Biomes.BLACKLIST_BOAR)) addMobSpawn(builder, biome, NaturalistTags.Biomes.HAS_BOAR, MobCategory.CREATURE, NaturalistEntityTypes.BOAR.get(), NaturalistConfig.COMMON_CONFIG.boarSpawnWeight.get(), NaturalistConfig.COMMON_CONFIG.boarSpawnMinGroupSize.get(), NaturalistConfig.COMMON_CONFIG.boarSpawnMaxGroupSize.get());
             if (NaturalistConfig.COMMON_CONFIG.butterflySpawnWeight.get() != 0 && !biome.is(NaturalistTags.Biomes.BLACKLIST_BUTTERFLY)) addMobSpawn(builder, biome, NaturalistTags.Biomes.HAS_BUTTERFLY, MobCategory.AMBIENT, NaturalistEntityTypes.BUTTERFLY.get(), NaturalistConfig.COMMON_CONFIG.butterflySpawnWeight.get(), NaturalistConfig.COMMON_CONFIG.butterflySpawnMinGroupSize.get(), NaturalistConfig.COMMON_CONFIG.butterflySpawnMaxGroupSize.get());
             if (NaturalistConfig.COMMON_CONFIG.canarySpawnWeight.get() != 0 && !biome.is(NaturalistTags.Biomes.BLACKLIST_CANARY)) addMobSpawn(builder, biome, NaturalistTags.Biomes.HAS_CANARY, MobCategory.CREATURE, NaturalistEntityTypes.CANARY.get(), NaturalistConfig.COMMON_CONFIG.canarySpawnWeight.get(), NaturalistConfig.COMMON_CONFIG.canarySpawnMinGroupSize.get(), NaturalistConfig.COMMON_CONFIG.canarySpawnMaxGroupSize.get());
             if (NaturalistConfig.COMMON_CONFIG.cardinalSpawnWeight.get() != 0 && !biome.is(NaturalistTags.Biomes.BLACKLIST_CARDINAL)) addMobSpawn(builder, biome, NaturalistTags.Biomes.HAS_CARDINAL, MobCategory.CREATURE, NaturalistEntityTypes.CARDINAL.get(), NaturalistConfig.COMMON_CONFIG.cardinalSpawnWeight.get(), NaturalistConfig.COMMON_CONFIG.cardinalSpawnMinGroupSize.get(), NaturalistConfig.COMMON_CONFIG.cardinalSpawnMaxGroupSize.get());
             if (NaturalistConfig.COMMON_CONFIG.catfishSpawnWeight.get() != 0 && !biome.is(NaturalistTags.Biomes.BLACKLIST_CATFISH)) addMobSpawn(builder, biome, NaturalistTags.Biomes.HAS_CATFISH, MobCategory.WATER_AMBIENT, NaturalistEntityTypes.CATFISH.get(), NaturalistConfig.COMMON_CONFIG.catfishSpawnWeight.get(), NaturalistConfig.COMMON_CONFIG.catfishSpawnMinGroupSize.get(), NaturalistConfig.COMMON_CONFIG.catfishSpawnMaxGroupSize.get());
             if (NaturalistConfig.COMMON_CONFIG.coralSnakeSpawnWeight.get() != 0 && !biome.is(NaturalistTags.Biomes.BLACKLIST_CORAL_SNAKE)) addMobSpawn(builder, biome, NaturalistTags.Biomes.HAS_CORAL_SNAKE, MobCategory.CREATURE, NaturalistEntityTypes.CORAL_SNAKE.get(), NaturalistConfig.COMMON_CONFIG.coralSnakeSpawnWeight.get(), NaturalistConfig.COMMON_CONFIG.coralSnakeSpawnMinGroupSize.get(), NaturalistConfig.COMMON_CONFIG.coralSnakeSpawnMaxGroupSize.get());
             if (NaturalistConfig.COMMON_CONFIG.deerSpawnWeight.get() != 0 && !biome.is(NaturalistTags.Biomes.BLACKLIST_DEER)) addMobSpawn(builder, biome, NaturalistTags.Biomes.HAS_DEER, MobCategory.CREATURE, NaturalistEntityTypes.DEER.get(), NaturalistConfig.COMMON_CONFIG.deerSpawnWeight.get(), NaturalistConfig.COMMON_CONFIG.deerSpawnMinGroupSize.get(), NaturalistConfig.COMMON_CONFIG.deerSpawnMaxGroupSize.get());
             if (NaturalistConfig.COMMON_CONFIG.dragonflySpawnWeight.get() != 0 && !biome.is(NaturalistTags.Biomes.BLACKLIST_DRAGONFLY)) addMobSpawn(builder, biome, NaturalistTags.Biomes.HAS_DRAGONFLY, MobCategory.AMBIENT, NaturalistEntityTypes.DRAGONFLY.get(), NaturalistConfig.COMMON_CONFIG.dragonflySpawnWeight.get(), NaturalistConfig.COMMON_CONFIG.dragonflySpawnMinGroupSize.get(), NaturalistConfig.COMMON_CONFIG.dragonflySpawnMaxGroupSize.get());
             if (NaturalistConfig.COMMON_CONFIG.duckSpawnWeight.get() != 0 && !biome.is(NaturalistTags.Biomes.BLACKLIST_DUCK)) addMobSpawn(builder, biome, NaturalistTags.Biomes.HAS_DUCK, MobCategory.CREATURE, NaturalistEntityTypes.DUCK.get(), NaturalistConfig.COMMON_CONFIG.duckSpawnWeight.get(), NaturalistConfig.COMMON_CONFIG.duckSpawnMinGroupSize.get(), NaturalistConfig.COMMON_CONFIG.duckSpawnMaxGroupSize.get());
             if (NaturalistConfig.COMMON_CONFIG.elephantSpawnWeight.get() != 0 && !biome.is(NaturalistTags.Biomes.BLACKLIST_ELEPHANT)) addMobSpawn(builder, biome, NaturalistTags.Biomes.HAS_ELEPHANT, MobCategory.CREATURE, NaturalistEntityTypes.ELEPHANT.get(), NaturalistConfig.COMMON_CONFIG.elephantSpawnWeight.get(), NaturalistConfig.COMMON_CONFIG.elephantSpawnMinGroupSize.get(), NaturalistConfig.COMMON_CONFIG.elephantSpawnMaxGroupSize.get());
             if (NaturalistConfig.COMMON_CONFIG.finchSpawnWeight.get() != 0 && !biome.is(NaturalistTags.Biomes.BLACKLIST_FINCH)) addMobSpawn(builder, biome, NaturalistTags.Biomes.HAS_FINCH, MobCategory.CREATURE, NaturalistEntityTypes.FINCH.get(), NaturalistConfig.COMMON_CONFIG.finchSpawnWeight.get(), NaturalistConfig.COMMON_CONFIG.finchSpawnMinGroupSize.get(), NaturalistConfig.COMMON_CONFIG.finchSpawnMaxGroupSize.get());
             if (NaturalistConfig.COMMON_CONFIG.fireflySpawnWeight.get() != 0 && !biome.is(NaturalistTags.Biomes.BLACKLIST_FIREFLY)) addMobSpawn(builder, biome, NaturalistTags.Biomes.HAS_FIREFLY, MobCategory.AMBIENT, NaturalistEntityTypes.FIREFLY.get(), NaturalistConfig.COMMON_CONFIG.fireflySpawnWeight.get(), NaturalistConfig.COMMON_CONFIG.fireflySpawnMinGroupSize.get(), NaturalistConfig.COMMON_CONFIG.fireflySpawnMaxGroupSize.get());
             if (NaturalistConfig.COMMON_CONFIG.forestFoxSpawnWeight.get() != 0 ) addMobSpawn(builder, biome, BiomeTags.IS_FOREST, MobCategory.CREATURE, EntityType.FOX, NaturalistConfig.COMMON_CONFIG.forestFoxSpawnWeight.get(), NaturalistConfig.COMMON_CONFIG.forestFoxSpawnMinGroupSize.get(), NaturalistConfig.COMMON_CONFIG.forestFoxSpawnMaxGroupSize.get());
             if (NaturalistConfig.COMMON_CONFIG.forestRabbitSpawnWeight.get() != 0 ) addMobSpawn(builder, biome, BiomeTags.IS_FOREST, MobCategory.CREATURE, EntityType.RABBIT, NaturalistConfig.COMMON_CONFIG.forestRabbitSpawnWeight.get(), NaturalistConfig.COMMON_CONFIG.forestRabbitSpawnMinGroupSize.get(), NaturalistConfig.COMMON_CONFIG.forestRabbitSpawnMaxGroupSize.get());
             if (NaturalistConfig.COMMON_CONFIG.giraffeSpawnWeight.get() != 0 && !biome.is(NaturalistTags.Biomes.BLACKLIST_GIRAFFE)) addMobSpawn(builder, biome, NaturalistTags.Biomes.HAS_GIRAFFE, MobCategory.CREATURE, NaturalistEntityTypes.GIRAFFE.get(), NaturalistConfig.COMMON_CONFIG.giraffeSpawnWeight.get(), NaturalistConfig.COMMON_CONFIG.giraffeSpawnMinGroupSize.get(), NaturalistConfig.COMMON_CONFIG.giraffeSpawnMaxGroupSize.get());
             if (NaturalistConfig.COMMON_CONFIG.hippoSpawnWeight.get() != 0 && !biome.is(NaturalistTags.Biomes.BLACKLIST_HIPPO)) addMobSpawn(builder, biome, NaturalistTags.Biomes.HAS_HIPPO, MobCategory.CREATURE, NaturalistEntityTypes.HIPPO.get(), NaturalistConfig.COMMON_CONFIG.hippoSpawnWeight.get(), NaturalistConfig.COMMON_CONFIG.hippoSpawnMinGroupSize.get(), NaturalistConfig.COMMON_CONFIG.hippoSpawnMaxGroupSize.get());
             if (NaturalistConfig.COMMON_CONFIG.lionSpawnWeight.get() != 0 && !biome.is(NaturalistTags.Biomes.BLACKLIST_LION)) addMobSpawn(builder, biome, NaturalistTags.Biomes.HAS_LION, MobCategory.CREATURE, NaturalistEntityTypes.LION.get(), NaturalistConfig.COMMON_CONFIG.lionSpawnWeight.get(), NaturalistConfig.COMMON_CONFIG.lionSpawnMinGroupSize.get(), NaturalistConfig.COMMON_CONFIG.lionSpawnMaxGroupSize.get());
             if (NaturalistConfig.COMMON_CONFIG.lizardSpawnWeight.get() != 0 && !biome.is(NaturalistTags.Biomes.BLACKLIST_LIZARD)) addMobSpawn(builder, biome, NaturalistTags.Biomes.HAS_LIZARD, MobCategory.CREATURE, NaturalistEntityTypes.LIZARD.get(), NaturalistConfig.COMMON_CONFIG.lizardSpawnWeight.get(), NaturalistConfig.COMMON_CONFIG.lizardSpawnMinGroupSize.get(), NaturalistConfig.COMMON_CONFIG.lizardSpawnMaxGroupSize.get());
             if (NaturalistConfig.COMMON_CONFIG.rhinoSpawnWeight.get() != 0 && !biome.is(NaturalistTags.Biomes.BLACKLIST_RHINO)) addMobSpawn(builder, biome, NaturalistTags.Biomes.HAS_RHINO, MobCategory.CREATURE, NaturalistEntityTypes.RHINO.get(), NaturalistConfig.COMMON_CONFIG.rhinoSpawnWeight.get(), NaturalistConfig.COMMON_CONFIG.rhinoSpawnMinGroupSize.get(), NaturalistConfig.COMMON_CONFIG.rhinoSpawnMaxGroupSize.get());
             if (NaturalistConfig.COMMON_CONFIG.robinSpawnWeight.get() != 0 && !biome.is(NaturalistTags.Biomes.BLACKLIST_ROBIN)) addMobSpawn(builder, biome, NaturalistTags.Biomes.HAS_ROBIN, MobCategory.CREATURE, NaturalistEntityTypes.ROBIN.get(), NaturalistConfig.COMMON_CONFIG.robinSpawnWeight.get(), NaturalistConfig.COMMON_CONFIG.robinSpawnMinGroupSize.get(), NaturalistConfig.COMMON_CONFIG.robinSpawnMaxGroupSize.get());
             if (NaturalistConfig.COMMON_CONFIG.snailSpawnWeight.get() != 0 && !biome.is(NaturalistTags.Biomes.BLACKLIST_SNAIL)) addMobSpawn(builder, biome, NaturalistTags.Biomes.HAS_SNAIL, MobCategory.CREATURE, NaturalistEntityTypes.SNAIL.get(), NaturalistConfig.COMMON_CONFIG.snailSpawnWeight.get(), NaturalistConfig.COMMON_CONFIG.snailSpawnMinGroupSize.get(), NaturalistConfig.COMMON_CONFIG.snailSpawnMaxGroupSize.get());
             if (NaturalistConfig.COMMON_CONFIG.snakeSpawnWeight.get() != 0 && !biome.is(NaturalistTags.Biomes.BLACKLIST_SNAKE)) addMobSpawn(builder, biome, NaturalistTags.Biomes.HAS_SNAKE, MobCategory.CREATURE, NaturalistEntityTypes.SNAKE.get(), NaturalistConfig.COMMON_CONFIG.snakeSpawnWeight.get(), NaturalistConfig.COMMON_CONFIG.snakeSpawnMinGroupSize.get(), NaturalistConfig.COMMON_CONFIG.snakeSpawnMaxGroupSize.get());
             if (NaturalistConfig.COMMON_CONFIG.sparrowSpawnWeight.get() != 0 && !biome.is(NaturalistTags.Biomes.BLACKLIST_SPARROW)) addMobSpawn(builder, biome, NaturalistTags.Biomes.HAS_SPARROW, MobCategory.CREATURE, NaturalistEntityTypes.SPARROW.get(), NaturalistConfig.COMMON_CONFIG.sparrowSpawnWeight.get(), NaturalistConfig.COMMON_CONFIG.sparrowSpawnMinGroupSize.get(), NaturalistConfig.COMMON_CONFIG.sparrowSpawnMaxGroupSize.get());
             if (NaturalistConfig.COMMON_CONFIG.tortoiseSpawnWeight.get() != 0 && !biome.is(NaturalistTags.Biomes.BLACKLIST_TORTOISE)) addMobSpawn(builder, biome, NaturalistTags.Biomes.HAS_TORTOISE, MobCategory.CREATURE, NaturalistEntityTypes.TORTOISE.get(), NaturalistConfig.COMMON_CONFIG.tortoiseSpawnWeight.get(), NaturalistConfig.COMMON_CONFIG.tortoiseSpawnMinGroupSize.get(), NaturalistConfig.COMMON_CONFIG.tortoiseSpawnMaxGroupSize.get());
             if (NaturalistConfig.COMMON_CONFIG.vultureSpawnWeight.get() != 0 && !biome.is(NaturalistTags.Biomes.BLACKLIST_VULTURE)) addMobSpawn(builder, biome, NaturalistTags.Biomes.HAS_VULTURE, MobCategory.CREATURE, NaturalistEntityTypes.VULTURE.get(), NaturalistConfig.COMMON_CONFIG.vultureSpawnWeight.get(), NaturalistConfig.COMMON_CONFIG.vultureSpawnMinGroupSize.get(), NaturalistConfig.COMMON_CONFIG.vultureSpawnMaxGroupSize.get());
             if (NaturalistConfig.COMMON_CONFIG.zebraSpawnWeight.get() != 0 && !biome.is(NaturalistTags.Biomes.BLACKLIST_ZEBRA)) addMobSpawn(builder, biome, NaturalistTags.Biomes.HAS_ZEBRA, MobCategory.CREATURE, NaturalistEntityTypes.ZEBRA.get(), NaturalistConfig.COMMON_CONFIG.zebraSpawnWeight.get(), NaturalistConfig.COMMON_CONFIG.zebraSpawnMinGroupSize.get(), NaturalistConfig.COMMON_CONFIG.zebraSpawnMaxGroupSize.get());
        }
    }

    void addMobSpawn(ModifiableBiomeInfo.BiomeInfo.Builder builder, Holder<Biome> biome, TagKey<Biome> tag, MobCategory mobCategory, EntityType<?> entityType, int weight, int minGroupSize, int maxGroupSize) {
        if (biome.is(tag)) {
            builder.getMobSpawnSettings().addSpawn(mobCategory, new MobSpawnSettings.SpawnerData(entityType, weight, minGroupSize, maxGroupSize));
        }
    }

    @Override
    public @NotNull MapCodec<? extends BiomeModifier> codec() {
        return NaturalistBiomeModifiers.ADD_ANIMALS_CODEC.get();
    }
}
