plugins {
    id "com.gradleup.shadow" version "8.3.5"
}

architectury {
    platformSetupLoomIde()
    neoForge()
}

loom {
    accessWidenerPath = project(":common").loom.accessWidenerPath

    runs {
        client {
            client()
            ideConfigGenerated true
            runDir "run"
        }
        server {
            server()
            ideConfigGenerated true
            runDir "run"
        }
    }
}

sourceSets.main.resources { srcDir "src/generated/resources" }

sourceSets.main.java.exclude "com/crispytwig/naturalist/datagen/**"

configurations {
    common
    shadowBundle
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentNeoForge.extendsFrom common
}

dependencies {
    neoForge "net.neoforged:neoforge:${project.neo_version}"


    modCompileOnly("dev.lambdaurora.lambdynamiclights:lambdynamiclights-api:${project.lambdynamiclights_version}") {
        attributes {
            attribute(Attribute.of("net.minecraft.mappings", String), "mojmap")
        }
    }

    common(project(path: ":common", configuration: "namedElements")) { transitive false }
    shadowBundle project(path: ":common", configuration: "transformProductionNeoForge")

    modLocalRuntime "maven.modrinth:spawn-mod:${project.spawn_version}"

    modCompileOnly "maven.modrinth:justenoughbreeding:${project.justenoughbreeding_neoforge_version}"
    modLocalRuntime "maven.modrinth:justenoughbreeding:${project.justenoughbreeding_neoforge_version}"

    modCompileOnly "maven.modrinth:emi:${project.emi_neoforge_version}"
    modLocalRuntime "maven.modrinth:emi:${project.emi_neoforge_version}"

    modLocalRuntime "maven.modrinth:field-guide:${project.field_guide_neoforge_version}"

    modLocalRuntime "maven.modrinth:immersive-overlays:${project.immersive_overlays_version}-neoforge"
}

processResources {
    def expandProps = [
            "mod_version"            : project.mod_version,
            "mod_id"                 : project.mod_id,
            "mod_name"               : project.mod_name,
            "mod_license"            : project.mod_license,
            "mod_description"        : project.mod_description,
            "mod_authors"            : project.mod_authors,
            "minecraft_version_range": project.minecraft_version_range,
            "neo_version"            : project.neo_version,
            "loader_version_range"   : project.loader_version_range
    ]

    filesMatching("META-INF/neoforge.mods.toml") {
        expand expandProps
    }
    inputs.properties(expandProps)
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = "dev-shadow"
}

remapJar {
    input.set shadowJar.archiveFile
    archiveClassifier = null
}

jar {
    archiveClassifier = "dev"
}
